import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const CLI = join(process.cwd(), "dist", "cli.js");

function run(args: string[], cwd: string): { stdout: string; stderr: string; status: number } {
  try {
    const stdout = execFileSync("node", [CLI, ...args], { cwd, encoding: "utf8" });
    return { stdout, stderr: "", status: 0 };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; status?: number };
    return { stdout: e.stdout ?? "", stderr: e.stderr ?? "", status: e.status ?? 1 };
  }
}

describe("computeledger CLI (built dist, end to end)", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "computeledger-cli-test-"));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("prints help with no arguments", () => {
    const result = run([], dir);
    expect(result.stdout).toContain("computeledger");
    expect(result.status).toBe(0);
  });

  it("generates keys, records usage, and verifies the receipt round-trip", () => {
    const gen = run(["keys", "generate", "--local"], dir);
    expect(gen.status).toBe(0);
    expect(existsSync(join(dir, ".computeledger", "keys", "ed25519.pem"))).toBe(true);

    const record = run(
      ["record", "--local", "--provider", "aws", "--hardware", "nvidia-h100", "--duration-seconds", "60", "--json"],
      dir
    );
    expect(record.status).toBe(0);
    const receipt = JSON.parse(record.stdout);
    expect(receipt.provider).toBe("aws");

    const receiptPath = join(dir, "receipt.json");
    writeFileSync(receiptPath, record.stdout);
    const verify = run(["verify", receiptPath, "--json"], dir);
    expect(verify.status).toBe(0);
    expect(JSON.parse(verify.stdout).valid).toBe(true);
  });

  it("rejects a tampered receipt on verify", () => {
    run(["keys", "generate", "--local"], dir);
    const record = run(
      ["record", "--local", "--provider", "aws", "--hardware", "cpu", "--duration-seconds", "5", "--json"],
      dir
    );
    const receipt = JSON.parse(record.stdout);
    receipt.usage.durationSeconds = 99999;
    const receiptPath = join(dir, "tampered.json");
    writeFileSync(receiptPath, JSON.stringify(receipt));

    const verify = run(["verify", receiptPath, "--json"], dir);
    expect(verify.status).toBe(1);
    expect(JSON.parse(verify.stdout).valid).toBe(false);
  });

  it("chains multiple ledger entries and passes ledger verify", () => {
    run(["keys", "generate", "--local"], dir);
    run(["record", "--local", "--provider", "aws", "--hardware", "cpu", "--duration-seconds", "1"], dir);
    run(["record", "--local", "--provider", "aws", "--hardware", "cpu", "--duration-seconds", "2"], dir);

    const list = run(["ledger", "list", "--local", "--json"], dir);
    const entries = JSON.parse(list.stdout);
    expect(entries).toHaveLength(2);
    expect(entries[1].prevHash).toBe(entries[0].hash);

    const verify = run(["ledger", "verify", "--local", "--json"], dir);
    expect(verify.status).toBe(0);
    expect(JSON.parse(verify.stdout).valid).toBe(true);
  });

  it("rejects a malformed command with a non-zero exit code, not a crash", () => {
    const result = run(["not-a-real-command"], dir);
    expect(result.status).toBe(1);
  });

  it("rejects a non-numeric --gpu-hours with a clean error, not a raw stack trace", () => {
    run(["keys", "generate", "--local"], dir);
    const result = run(
      ["record", "--local", "--provider", "aws", "--hardware", "cpu", "--duration-seconds", "1", "--gpu-hours", "not-a-number", "--json"],
      dir
    );
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("--gpu-hours must be a non-negative number");
    expect(result.stderr).not.toContain("at Object");
  });

  it("keys show prints the public key generated by keys generate", () => {
    run(["keys", "generate", "--local"], dir);
    const show = run(["keys", "show", "--local", "--json"], dir);
    expect(show.status).toBe(0);
    expect(JSON.parse(show.stdout).publicKey).toMatch(/^[A-Za-z0-9+/]+=*$/);
  });

  it("run wraps a real command, measures duration, and appends a receipt", () => {
    run(["keys", "generate", "--local"], dir);
    const result = run(["run", "--local", "--provider", "on-prem", "--hardware", "cpu", "--json", "--", "node", "-e", "1+1"], dir);
    expect(result.status).toBe(0);
    const receipt = JSON.parse(result.stdout);
    expect(receipt.provider).toBe("on-prem");
    expect(receipt.command).toBe("node -e 1+1");
    expect(receipt.usage.durationSeconds).toBeGreaterThanOrEqual(0);
  });

  it("run --no-record-command omits the command text from the receipt", () => {
    run(["keys", "generate", "--local"], dir);
    const result = run(
      ["run", "--local", "--provider", "on-prem", "--hardware", "cpu", "--no-record-command", "--json", "--", "node", "-e", "1"],
      dir
    );
    const receipt = JSON.parse(result.stdout);
    expect(receipt.command).toBeNull();
  });

  it("run propagates the wrapped command's non-zero exit code", () => {
    run(["keys", "generate", "--local"], dir);
    const result = run(["run", "--local", "--provider", "aws", "--hardware", "cpu", "--", "node", "-e", "process.exit(7)"], dir);
    expect(result.status).toBe(7);
  });

  it("export writes JSON and CSV ledger dumps to a file", () => {
    run(["keys", "generate", "--local"], dir);
    run(["record", "--local", "--provider", "aws", "--hardware", "cpu", "--duration-seconds", "1"], dir);

    const jsonOut = join(dir, "out.json");
    const jsonResult = run(["export", "--local", "--format", "json", "--out", jsonOut], dir);
    expect(jsonResult.status).toBe(0);
    expect(existsSync(jsonOut)).toBe(true);
    expect(JSON.parse(readFileSync(jsonOut, "utf8"))).toHaveLength(1);

    const csvOut = join(dir, "out.csv");
    const csvResult = run(["export", "--local", "--format", "csv", "--out", csvOut], dir);
    expect(csvResult.status).toBe(0);
    expect(readFileSync(csvOut, "utf8")).toContain("id,timestamp,provider,hardware");
  });
});
